spring:
   application:
      name: AsyncConsumer
   profiles:
      include: rabbitmq-setup-props, executors-props, producer-props
      #, datasource-props
   rabbitmq:
      #host: ${rabbitmq_host}
      #port: ${rabbitmq_port}
      addresses: ${rabbitmq_address}
      username: ${rabbitmq_username}
      password: ${rabbitmq_password}      
logging:
   level:
      Root: ${log_level}
      org.springframework.web.filter.CommonsRequestLoggingFilter: INFO
      com.zaxxer.hikari.HikariConfig: INFO
      com.zaxxer.hikari.pool.HikariPool: DEBUG
   pattern:
      console: "%d [%thread] %-5level %logger{36} - %msg %mdc%n"   
management:
   server:
      port: 9871
      ssl:
         enabled: false
   endpoints:
      web:
         base-path: /sssactuator
         exposure:
            include: "*"
      
