spring:
  application:
    name: AsyncConsumer
  profiles:
    group:
       local: rabbitmq-setup-props-local, executors-props-local, producer-props-local
       dev: rabbitmq-setup-props-dev, executors-props-dev, producer-props-dev, datasource-props-dev
       prod: rabbitmq-setup-props-prod, executors-props-prod, producer-props-prod, datasource-props-prod
  cloud:
    config:
      server:
        bootstrap: true