spring:
  application:
    name: AsyncConsumer
 #--profile group/include are adding files from class path but not from confihg server, please pass it from run arguments
  #profiles:
    #group:
      #docker-local: rabbitmq-setup-local,executors-local,producer-local
      #local: rabbitmq-setup-local,executors-local,producer-local
      #dev: rabbitmq-setup-dev,executors-dev,producer-dev,datasource-dev
      #prod: rabbitmq-setup-prod,executors-prod,producer-prod,datasource-prod  
        
  cloud:
    config:
      server:
        bootstrap: true