spring:
   application:
      name: AsyncConsumer
   rabbitmq:
#host: b-74c42180-ee61-4e4f-ae74-39f5ff7a7f67.mq.us-east-2.amazonaws.com
#port: 5671
      addresses: localhost:5672
      username: guest
      password: guest
      ssl:
         enabled: false
#logging:
#   level:
#      Root: INFO
#      org.springframework.web.filter.CommonsRequestLoggingFilter: INFO
#      com.zaxxer.hikari.HikariConfig: INFO
#      com.zaxxer.hikari.pool.HikariPool: DEBUG
#   pattern:
#      console: "%d [%thread] %-5level %logger{36} - %msg %mdc%n"
management:
   server:
      ssl:
         enabled: false
   endpoints:
      web:
#base-path: /sssactuator
         exposure:
            include: '*'