jmuscles:
   executors-config:
      restConfig:
         connectionTimeout: 10000
         readTimeout: 10000
      restCalls:
         calculator_soap:
            url: http://www.dneonline.com/calculator.asmx
            validator: SimpleSoapCallValidator
            successCodePatterns:
               200: null
         countryinfoservice_soap:
            url: http://webservices.oorsprong.org/websamples.countryinfo/CountryInfoService.wso
            validator: SimpleSoapCallValidator
            successCodePatterns:
               200: null
         numberconversion_soap:
            url: https://www.dataaccess.com/webservicesserver/NumberConversion.wso
            validator: SimpleSoapCallValidator
            successCodePatterns:
               200: null
         isbnservice_soap:
            url: http://webservices.daehosting.com/services/isbnservice.wso
            validator: SimpleSoapCallValidator
            successCodePatterns:
               200: null
         tempconvert_soap:
            url: http://www.w3schools.com/xml/tempconvert.asmx
            validator: SimpleSoapCallValidator
            successCodePatterns:
               200: null
         reqres:
            url: https://reqres.in
            successCodePatterns:
               200: null
         restcountries:
            url: https://restcountries.com/v3.1
            successCodePatterns:
               200: null
         jsonplaceholderpost:
            url: https://jsonplaceholder.typicode.com/posts
            successCodePatterns:
               200: null
               201: null
               
               